### PR TITLE
Lock event-stream@3.3.4 due to security vulnerability

### PR DESCRIPTION
**Pull request by code-for-coffee**
Hey @mjackson! I was starting to play with this after your session in Chicago. I found it included the vulnerability disclosed today in event-stream@3.3.5 (noted in https://github.com/dominictarr/event-stream/issues/116#issuecomment-441745900) so I locked this package's version to the prior version. I have not had time to run any tests on it but since the only commit change looks to be a malicious code block being inserted into 3.3.5 this *hopefully* works as intended. I'll test in the AM when I have had sleep if your CI builds don't catch anything.

### CODE REVIEW

**Comment by mikemorris** [comment]
Guessing we don't want to add a `package-lock.json` in addition to the `yarn.lock` file? Otherwise looks good.

**Comment by code-for-coffee** [comment]
@mikemorris I am not sure myself since I had to install yarn to generate the `yarn.lock` file. I provided both to satisfy npm/yarn users but I believe yarn doesn't like the package-lock.json being included.

**Comment by mjackson** [comment]
Thanks, @code-for-coffee. And thanks for suggesting we remove the `package-lock.json`, @mikemorris. I'll take care of that.

**Comment by mjackson** [comment]
Just FYI: This was just released in [version 3.4.7](https://github.com/ReactTraining/react-stdio/releases/tag/v3.4.7).

**Pull request merged**
